
services:
  db:
    image: postgres:latest
    container_name: tourplanner_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#psql -U user -d tourplanner um in docker desktop zu schreiben

#dotnet ef database updateted automatisch table erstellen